% id_data = load('id_data.mat');

x_train = id_data.train(1:end-1, 2:end)';
y_train = id_data.train(2:end,  [10, 11, 15, 16, 17, 18] + 1)';
x_test = id_data.test(1:end-1, 2:end)';
y_test = id_data.test(2:end,  [10, 11, 15, 16, 17, 18] + 1)';

numFeatures = size(x_train, 1);
numHiddenUnits = 10;
numResponses = size(y_train, 1);

layers = [ ...
    sequenceInputLayer(numFeatures)
    lstmLayer(numHiddenUnits)
    fullyConnectedLayer(numResponses)
    regressionLayer];

options = trainingOptions('adam', ...
    'MaxEpochs', 10000, ...
    'GradientThreshold', 1, ...
    'InitialLearnRate', 0.01, ...
    'LearnRateSchedule', 'piecewise', ...
    'LearnRateDropPeriod', 1000, ...
    'LearnRateDropFactor', 0.2, ...
    'ValidationData',{x_test, y_test}, ...
    'ValidationFrequency', 10, ...
    'Verbose', 1, ...
    'Plots','training-progress');

net = trainNetwork(x_train, y_train, layers, options);
