services:

  base:
    build:
      context: . 
      dockerfile: docker/Dockerfile.base
    container_name: racing_base
    image: car-base
    env_file:
      - docker/shared.env
    networks:
      - racing_network
    entrypoint: ""


  # Perception system
  perception:
    build:
      context: .
      dockerfile: docker/Dockerfile.perception
    container_name: racing_perception
    image: car-perception
    depends_on:
      - base
    env_file:
      - docker/shared.env
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/root/.Xauthority
    volumes:
      - ./logs:/workspace/logs
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY:-~/.Xauthority}:/root/.Xauthority:ro
      # mounting source code so code changes don't need a rebuild
      - ./perception_ws/src:/workspace/perception_ws/src:rw
      - ./best.pt:/workspace/perception_ws/models/best.pt:ro
    networks:
      - racing_network
    stdin_open: true
    tty: true
    entrypoint: ["/entrypoint.sh"]
    command: >
      bash -c "
      echo 'Perception ready. Start nodes manually or run: ros2 run cone_detector YOLO_cone_detector' &&
      tail -f /dev/null
      "

  # Path planning
  path_planning:
    build:
      context: .
      dockerfile: docker/Dockerfile.planning
    container_name: racing_planning
    image: car-planning
    depends_on:
      - perception
    env_file:
      - docker/shared.env
    volumes:
      - ./logs:/workspace/logs
    networks:
      - racing_network
    entrypoint: ""
    command: >
      bash -c "
      echo '🛣️ Starting path planning...' &&
      source /opt/ros/humble/setup.bash &&
      source /workspace/planning_ws/install/setup.bash &&
      /workspace/planning_ws/install/path_planning/bin/path_planner
      "

  # Control system
  control:
    build:
      context: .
      dockerfile: docker/Dockerfile.control
    container_name: racing_control
    image: car-control
    depends_on:
      - path_planning
    env_file:
      - docker/shared.env
    volumes:
      - ./Control:/workspace/Control
      - ./Control/logs:/workspace/logs
    #networks:
    #  - racing_network
    cap_add:
      - NET_ADMIN
    network_mode: host
    ports:      
      - "7400:7400/udp"
    entrypoint: ["/entrypoint.sh"]

  eufs_sim:
    build:
      context: .
      dockerfile: docker/Dockerfile.eufs_sim
    container_name: racing_eufs_sim
    image: car-eufs
    depends_on:
      - base
      - perception
    env_file:
      - docker/shared.env
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/root/.Xauthority
      - TRACK_NAME=${TRACK_NAME:-small_track}
    networks:
      - racing_network
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY:-~/.Xauthority}:/root/.Xauthority:ro
      - ./Control:/workspace/Control:rw
      - ./config/racing_visualization.rviz:/workspace/racing.rviz:ro
    stdin_open: true
    tty: true

networks:
  racing_network:
    driver: bridge

volumes:
  logs: