set(_AMENT_PACKAGE_NAME "slam_example")
set(slam_example_VERSION "0.0.0")
set(slam_example_MAINTAINER "ritvik <ritvik.bharamgoudar@gmail.com>")
set(slam_example_BUILD_DEPENDS "rclcpp" "sensor_msgs" "nav_msgs" "cv_bridge" "OpenCV" "message_filters")
set(slam_example_BUILDTOOL_DEPENDS "ament_cmake")
set(slam_example_BUILD_EXPORT_DEPENDS "rclcpp" "sensor_msgs" "nav_msgs" "cv_bridge" "OpenCV" "message_filters")
set(slam_example_BUILDTOOL_EXPORT_DEPENDS )
set(slam_example_EXEC_DEPENDS "rclcpp" "sensor_msgs" "nav_msgs" "cv_bridge" "OpenCV" "message_filters")
set(slam_example_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(slam_example_GROUP_DEPENDS )
set(slam_example_MEMBER_OF_GROUPS )
set(slam_example_DEPRECATED "")
set(slam_example_EXPORT_TAGS)
list(APPEND slam_example_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
