function net = cnn_init_cones(Nclasses, h, w, dim)

in = zeros(h, w, dim, 'single');
labels = zeros(1, 1, 'single');
rng('default');
rng(0) ;
dropout = 0.05;
f = 1/100 ;
net.layers = {} ;
% BLOCK 1
net.layers{end+1} = struct('type', 'conv', ...
    'weights', {{f * randn(5, 5, dim, 6, 'single'), zeros(1, 6, 'single')}}, ...
    'stride', 1, ...
    'pad', 2);
net = vl_simplenn_tidy(net); res = vl_simplenn(net, in);
fprintf('in: %d x %d x %d --> out: %d x %d x %d\n', ...
    size(res(end - 1).x, 1), size(res(end - 1).x, 2), size(res(end - 1).x, 3), ...
    size(res(end).x, 1), size(res(end).x, 2), size(res(end).x, 3));

net.layers{end+1} = struct('type', 'dropout', 'rate', dropout);

net.layers{end+1} = struct('type', 'pool', ...
    'method', 'max', ...
    'pool', [3 3], ...
    'stride', 3, ...
    'pad', 0) ;
net = vl_simplenn_tidy(net); res = vl_simplenn(net, in);
fprintf('in: %d x %d x %d --> out: %d x %d x %d\n', ...
    size(res(end - 1).x, 1), size(res(end - 1).x, 2), size(res(end - 1).x, 3), ...
    size(res(end).x, 1), size(res(end).x, 2), size(res(end).x, 3));

net.layers{end+1} = struct('type', 'relu') ;
net = vl_simplenn_tidy(net); res = vl_simplenn(net, in);
fprintf('in: %d x %d x %d --> out: %d x %d x %d\n', ...
    size(res(end - 1).x, 1), size(res(end - 1).x, 2), size(res(end - 1).x, 3), ...
    size(res(end).x, 1), size(res(end).x, 2), size(res(end).x, 3));

% BLOCK 2
net.layers{end+1} = struct('type', 'conv', ...
    'weights', {{f*randn(3, 3, 6, 8, 'single'),zeros(1, 8,'single')}}, ...
    'stride', 1, ...
    'pad', 1) ;
net = vl_simplenn_tidy(net); res = vl_simplenn(net, in);
fprintf('in: %d x %d x %d --> out: %d x %d x %d\n', ...
    size(res(end - 1).x, 1), size(res(end - 1).x, 2), size(res(end - 1).x, 3), ...
    size(res(end).x, 1), size(res(end).x, 2), size(res(end).x, 3));

net.layers{end+1} = struct('type', 'dropout', 'rate', dropout);

net.layers{end+1} = struct('type', 'pool', ...
    'method', 'max', ...
    'pool', [2 3], ...
    'stride', [2 3], ...
    'pad', 0);
net = vl_simplenn_tidy(net); res = vl_simplenn(net, in);
fprintf('in: %d x %d x %d --> out: %d x %d x %d\n', ...
    size(res(end - 1).x, 1), size(res(end - 1).x, 2), size(res(end - 1).x, 3), ...
    size(res(end).x, 1), size(res(end).x, 2), size(res(end).x, 3));

net.layers{end+1} = struct('type', 'relu') ;
net = vl_simplenn_tidy(net); res = vl_simplenn(net, in);
fprintf('in: %d x %d x %d --> out: %d x %d x %d\n', ...
    size(res(end - 1).x, 1), size(res(end - 1).x, 2), size(res(end - 1).x, 3), ...
    size(res(end).x, 1), size(res(end).x, 2), size(res(end).x, 3));


% BLOCK 3
net.layers{end+1} = struct('type', 'conv', ...
    'weights', {{f * randn(3, 3, 8, 16, 'single'), zeros(1, 16, 'single')}}, ...
    'stride', 1, ...
    'pad', 1) ;
net = vl_simplenn_tidy(net); res = vl_simplenn(net, in);
fprintf('in: %d x %d x %d --> out: %d x %d x %d\n', ...
    size(res(end - 1).x, 1), size(res(end - 1).x, 2), size(res(end - 1).x, 3), ...
    size(res(end).x, 1), size(res(end).x, 2), size(res(end).x, 3));

net.layers{end+1} = struct('type', 'dropout', 'rate', dropout);

net.layers{end+1} = struct('type', 'pool', ...
    'method', 'max', ...
    'pool', [4 2], ...
    'stride', [4 2], ...
    'pad', 0);
net = vl_simplenn_tidy(net); res = vl_simplenn(net, in);
fprintf('in: %d x %d x %d --> out: %d x %d x %d\n', ...
    size(res(end - 1).x, 1), size(res(end - 1).x, 2), size(res(end - 1).x, 3), ...
    size(res(end).x, 1), size(res(end).x, 2), size(res(end).x, 3));

net.layers{end+1} = struct('type', 'relu') ;
net = vl_simplenn_tidy(net); res = vl_simplenn(net, in);
fprintf('in: %d x %d x %d --> out: %d x %d x %d\n', ...
    size(res(end - 1).x, 1), size(res(end - 1).x, 2), size(res(end - 1).x, 3), ...
    size(res(end).x, 1), size(res(end).x, 2), size(res(end).x, 3));

% FC
net.layers{end+1} = struct('type', 'conv', ...
    'weights', {{f*randn(1, 1, 16, Nclasses, 'single'),  zeros(1, Nclasses, 'single')}}, ...
    'stride', 1, ...
    'pad', 0) ;
net = vl_simplenn_tidy(net); res = vl_simplenn(net, in);
fprintf('in: %d x %d x %d --> out: %d x %d x %d\n', ...
    size(res(end - 1).x, 1), size(res(end - 1).x, 2), size(res(end - 1).x, 3), ...
    size(res(end).x, 1), size(res(end).x, 2), size(res(end).x, 3));


net.layers{end+1} = struct('type', 'softmaxloss') ;


% net = insertBnorm(net, 1);
% net = insertBnorm(net, 5);
% net = insertBnorm(net, 9);
% net = insertBnorm(net, 13);


net = vl_simplenn_tidy(net);
vl_simplenn_display(net);

% --------------------------------------------------------------------
function net = insertBnorm(net, l)
% --------------------------------------------------------------------
assert(isfield(net.layers{l}, 'weights'));
ndim = size(net.layers{l}.weights{1}, 4);
layer = struct('type', 'bnorm', ...
               'weights', {{ones(ndim, 1, 'single'), zeros(ndim, 1, 'single')}}, ...
               'learningRate', [1 1 0.05], ...
               'weightDecay', [0 0]) ;
net.layers{l}.biases = [] ;
net.layers = horzcat(net.layers(1:l), layer, net.layers(l+1:end)) ;
