before = load('../../car_data/test_days/2019-12-11/recording0_calib/stereoParams.mat');
before = before.stereoParams;
after = load('../../car_data/test_days/2019-12-11/recording0_calib_post/stereoParams.mat');
after = after.stereoParams;

t_before = before.TranslationOfCamera2;
fprintf('TRANSLATION:\n');
fprintf('Before:     % .3f % .3f % .3f mm\n', ...
    t_before(1), ...
    t_before(2), ...
    t_before(3));

t_after = after.TranslationOfCamera2;
fprintf('After:      % .3f % .3f % .3f mm\n', ...
    t_after(1), ...
    t_after(2), ...
    t_after(3));

d = t_after - t_before;
fprintf('Difference:   % .3f % .3f % .3f mm\n\n', ...
    d(1), ...
    d(2), ...
    d(3));

rot_before = rad2deg(rodrigues(before.RotationOfCamera2));
rot_after = rad2deg(rodrigues(after.RotationOfCamera2));
d = rot_after - rot_before;

fprintf('ROTATION:\n');
fprintf('Before:     % .3f % .3f % .3f degrees\n', ...
    rot_before(1), ...
    rot_before(2), ...
    rot_before(3));
fprintf('After:      % .3f % .3f % .3f degrees\n', ...
    rot_after(1), ...
    rot_after(2), ...
    rot_after(3));
fprintf('Difference: % .3f % .3f % .3f degrees\n', ...
    d(1), ...
    d(2), ...
    d(3));
